highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: FÃ¡bio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
# baseurl: /vitae/
title: John Wolfe's Resume
name: John Wolfe
email: jwolfe890@gmail.com
email_full: mailto:jwolfe890@gmail.com
website: johnwolfe.tech
website_full: https://www.johnwolfe.tech
github: jwolfe890
twitter: jwolfe820
tel: (646) 379-1272
tel_full: tel:(646) 379-1272
address: 11 Saint Felix St. 
postcode: 11217
city: Brooklyn
country: New York
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
